<?php
$title = 'Genre';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('genre', ['action' => 'add']) ?>">Add new genre</a>
</p>

<table class="table">
    <tr>
        <th>Name</th>
    </tr>
    <?php foreach ($this->genres as $genre) : ?>
        <?php /** @var \Genre\Model\Genre $genre */ ?>
        <tr>
            <td><?= $this->escapeHtml($genre->getName()) ?></td>
            <td>
                <a href="<?= $this->url('genre', ['action' => 'edit', 'id' => $genre->getId()]) ?>">Edit</a>
                <a href="<?= $this->url('genre', ['action' => 'delete', 'id' => $genre->getId()]) ?>">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
