<?php
$title = 'Actor';
$this->headTitle($title);
?>
<h1><?= $this->escapeHtml($title) ?></h1>
<p>
    <a href="<?= $this->url('actor', ['action' => 'add']) ?>">Add new actor</a>
</p>

<table class="table">
    <tr>
        <th>Name</th>
    </tr>
    <?php foreach ($this->actors as $actor) : ?>
        <?php /** @var \Actor\Model\Actor $actor */ ?>
        <tr>
            <td><?= $this->escapeHtml($actor->getLastName()) ?></td>
            <td><?= $this->escapeHtml($actor->getFirstName()) ?></td>
            <td>
                <a href="<?= $this->url('actor', ['action' => 'edit', 'id' => $actor->getId()]) ?>">Edit</a>
                <a href="<?= $this->url('actor', ['action' => 'delete', 'id' => $actor->getId()]) ?>">Delete</a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>
